// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/add.post').default>>>>
    }
    '/api/delete': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delete.get').default>>>>
    }
    '/api/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login').default>>>>
    }
    '/api/queryall': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/queryall.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}